 language: scala
 scala:
   - "2.10.4"
   - "2.11.2"
 jdk:
   - openjdk6
   - openjdk7
   - oraclejdk8
notifications:
     email:
         recipients:
             - vidyac.raghav@gmail.com
             - buildsampletest@gmail.com
         on_success: change
         on_failure: always
